source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.0.2"

gem "rails", "~> 6.1.4", ">= 6.1.4.1"
gem "mysql2", "~> 0.5"
gem "puma", "~> 5.0"
gem "bootsnap", ">= 1.4.4", require: false
gem "rack-cors", "~> 1.1", ">= 1.1.1"
gem "devise", "~> 4.8"
gem "omniauth", "~> 2.0", ">= 2.0.4"
gem "omniauth-google-oauth2", "~> 1.0"
gem "omniauth-facebook", "~> 8.0"
gem "omniauth-rails_csrf_protection", "~> 1.0"
gem "omniauth-twitter", "~> 1.4"
gem "figaro", "~> 1.2"
gem "faker", "~> 2.19"
gem 'bcrypt', '~> 3.1', '>= 3.1.16'

group :development, :test do
  gem "byebug", platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  gem "listen", "~> 3.3"
  gem "spring"
end

gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]
